### ISSUE TITLE
Submission stream seems to stop behaving properly after 5XX errors

### ISSUE THREAD

**Issue by LovecraftianHorror** [LovecraftianHorror/rust_text_classifier#9]
It seems like the submission stream seems to totally lock up after there is a 5XX error with reddit's servers. It's possible that the submission stream has to be reset or there needs to be a reauth after these errors to fix them since there has been no obvious issues other than the submission stream waiting permanently without seeing new posts. `praw`s documentation doesn't seem to mention anything in particular so this will likely need to be experimented with

**Comment by LovecraftianHorror** [comment]
Logging to a file is setup now, so it should be easier to trackdown these errors as they occur

**Comment by LovecraftianHorror** [comment]
Currently the only error I've seen is `prawcore.exceptions.ServerError`. Traceback here

```text
[2021-07-09 23:47:59,661] WARNING: Traceback (most recent call last):
  File "/opt/rust_text_classifier/lib/bot/__init__.py", line 71, in run
    for submission in submission_stream:
  File "/usr/lib/python3/dist-packages/praw/models/util.py", line 170, in stream_generator
    for item in reversed(list(function(
  File "/usr/lib/python3/dist-packages/praw/models/listing/generator.py", line 52, in __next__
    self._next_batch()
  File "/usr/lib/python3/dist-packages/praw/models/listing/generator.py", line 62, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/usr/lib/python3/dist-packages/praw/reddit.py", line 408, in get
    data = self.request('GET', path, params=params)
  File "/usr/lib/python3/dist-packages/praw/reddit.py", line 533, in request
    return self._core.request(method, path, data=data, files=files,
  File "/usr/lib/python3/dist-packages/prawcore/sessions.py", line 183, in request
    return self._request_with_retries(
  File "/usr/lib/python3/dist-packages/prawcore/sessions.py", line 127, in _request_with_retries
    return self._do_retry(data, files, json, method, params, response,
  File "/usr/lib/python3/dist-packages/prawcore/sessions.py", line 92, in _do_retry
    return self._request_with_retries(
  File "/usr/lib/python3/dist-packages/prawcore/sessions.py", line 127, in _request_with_retries
    return self._do_retry(data, files, json, method, params, response,
  File "/usr/lib/python3/dist-packages/prawcore/sessions.py", line 92, in _do_retry
    return self._request_with_retries(
  File "/usr/lib/python3/dist-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.ServerError: received 503 HTTP response
```

**Comment by LovecraftianHorror** [comment]
Confirming now that the same error happened again and new submissions stopped being received afterwards. It looks like at the very least the stream has to be reset and we'll go from there

**Comment by LovecraftianHorror** [comment]
I've switched to just keeping a subreddit object and querying that instead of dealing with the stream since it seems to get in a weird state after throwing some exceptions and I'd rather eat the ~20loc complexity than deal with weird behavior.

If the subreddit object also gets into a weird state after throwing errors, then I may rethink things and switch back
